name: Test
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .editorconfig
      - .gitignore
jobs:
  example:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Example
        uses: miRoox/wolfram-action@v1
        with:
          file: Example/RunTests.wls
        env:
          WOLFRAM_ID: ${{ secrets.WolframID }}
          WOLFRAM_PASS: ${{ secrets.WolframPW }}
